#! /bin/sh

# launch sxhkd
sxhkd &

# set cursor to a pointer instead of a cross (bspwm background)
xsetroot -cursor_name left_ptr

# start compton
compton --config $HOME/.config/compton/compton.conf -b

# set background
[ -f $HOME/.fehbg ] && $HOME/.fehbg

# polybar
$HOME/.config/polybar/launch.sh

# actual config
bspc monitor eDP1 -d term web code misc gfx

bspc config border_width         4
bspc config window_gap          14

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^5' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Nm-connection-editor state=floating
bspc rule -a Zathura state=tiled

bspc config normal_border_color    $(xrdb -q | grep color3 | cut -f2) # yellow
bspc config focused_border_color   $(xrdb -q | grep color2 | cut -f2) # green
bspc config urgent_border_color    $(xrdb -q | grep color1 | cut -f2) # red
bspc config presel_feedback_color  $(xrdb -q | grep color4 | cut -f2) # blue
